# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "fedora33" do |fedora33|
    fedora33.vm.box = "generic/fedora33"
    fedora33.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--delete"]
    fedora33.vm.provision "shell", :path => "build-rpm.sh", :args => "fedora33", :privileged => false
  end

  config.vm.define "fedora34" do |fedora34|
    fedora34.vm.box = "messyzone/fedora34"
    fedora34.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--delete"]
    fedora34.vm.provision "shell", :path => "build-rpm.sh", :args => "fedora34", :privileged => false
  end

  config.vm.define "centos7" do |centos7|
    centos7.vm.box = "centos/7"
    centos7.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--copy-links"]
    centos7.vm.provision "shell", :path => "build-rpm.sh", :args => "centos7", :privileged => false
  end

  config.vm.define "centos8" do |centos8|
    centos8.vm.box = "zyz/centos8"
    centos8.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--copy-links"]
    centos8.vm.provision "shell", :path => "build-rpm.sh", :args => "centos8", :privileged => false
  end

  config.vm.define "debian9" do |debian9|
    debian9.vm.box = "roboxes/debian9"
    debian9.vm.synced_folder "../..", "/shared"
    debian9.vm.provision "shell", :path => "build-pkg.sh", :args => "debian9", :privileged => false
  end

  config.vm.define "debian10" do |debian10|
    debian10.vm.box = "roboxes/debian10"
    debian10.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--delete"]
    debian10.vm.provision "shell", :path => "build-pkg.sh", :args => "debian10", :privileged => false
  end

  config.vm.define "trusty" do |trusty|
    trusty.vm.box = "ubuntu/trusty64"
    trusty.vm.synced_folder "../..", "/shared"
    trusty.vm.provision "shell", :path => "build-pkg.sh", :args => "ubuntu1404", :privileged => false
  end

  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "ubuntu/xenial64"
    xenial.vm.synced_folder "../..", "/shared"
    xenial.vm.provision "shell", :path => "build-pkg.sh", :args => "ubuntu1604", :privileged => false
  end

  config.vm.define "bionic" do |bionic|
    bionic.vm.box = "ubuntu/bionic64"
    bionic.vm.synced_folder "../..", "/shared"
    bionic.vm.provision "shell", :path => "build-pkg.sh", :args => "ubuntu1804", :privileged => false
  end

  config.vm.define "focal" do |focal|
    focal.vm.box = "generic/ubuntu2004"
    focal.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--copy-links"]
    focal.vm.provision "shell", :path => "build-pkg.sh", :args => "ubuntu2004", :privileged => false
  end

  config.vm.define "hirsute" do |hirsute|
    hirsute.vm.box = "ubuntu/hirsute64"
    hirsute.vm.synced_folder "../..", "/shared", type: "rsync",
      rsync__args: ["--verbose", "--archive", "-z", "--copy-links"]
    hirsute.vm.provision "shell", :path => "build-pkg.sh", :args => "ubuntu2104", :privileged => false
  end

end
