name: Ubuntu with OpenSSL 1.1
on: [push]

jobs:
  openssl_1_1_build:
    name: Build with OpenSSL 1.1
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Install prerequisites
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set -x
          sudo apt update
          sudo apt install -q -y build-essential  \
                            cmake pkg-config      \
                            gengetopt             \
                            help2man              \
                            libcurl4-openssl-dev  \
                            libedit-dev           \
                            libpcsclite-dev       \
                            libusb-1.0-0-dev      \
                            file                  \
                            curl                  \
                            jq                    \
                            opensc

      - name: Install OpenSSL 1.1 from source
        run: |
          set -x
          
          echo $GITHUB_WORKSPACE
          
          wget -nv  https://github.com/openssl/openssl/archive/refs/tags/OpenSSL_1_1_1w.tar.gz
          tar -xzf OpenSSL_1_1_1w.tar.gz
          cd openssl-OpenSSL_1_1_1w
          ./Configure linux-x86_64 shared --prefix=$GITHUB_WORKSPACE/yubihsm-shell/openssl
          sudo make all install VERSION="1.1.1s"


      - name: prepare ghostunnel
        env:
          TLSPWD: ${{ secrets.TLSKEY }}
          # GODEBUG required for ghostunnel to temporarily enable Common Name matching
          GODEBUG: x509ignoreCN=0
        run: |
          curl -o /tmp/ghostunnel -L https://github.com/ghostunnel/ghostunnel/releases/download/v1.6.0/ghostunnel-v1.6.0-linux-amd64
          chmod +x /tmp/ghostunnel
          openssl aes-256-cbc \
            -k "$TLSPWD" \
            -md sha256 \
            -in .ci/client-combined.pem.enc \
            -out .ci/client-combined.pem \
            -d
          /tmp/ghostunnel client \
            --listen localhost:12345 \
            --target hsm-connector01.sthlm.in.yubico.org:8443 \
            --keystore .ci/client-combined.pem \
            --cacert .ci/server-crt.pem > /dev/null 2>&1 &
          sleep 3
          DEFAULT_CONNECTOR_URL=$(curl -s http://localhost:12345/dispatcher/request)
          test -n "$DEFAULT_CONNECTOR_URL" || (echo "Unable to obtain a connector URL, aborting"; exit 1)
          echo "DEFAULT_CONNECTOR_URL=$DEFAULT_CONNECTOR_URL" >> $GITHUB_ENV          

      - name: Build
        run: |
          set -x
          mkdir build; cd build
          cmake .. -DVERBOSE_CMAKE=ON -DOPENSSL_PKG_PATH=$GITHUB_WORKSPACE/yubihsm-shell/openssl/lib/pkgconfig
          make
          ./src/yubihsm-shell --help | grep "Usage: yubihsm-shell"

      - name: Test EC signature
        run: |
          cd build
          echo "connector=$DEFAULT_CONNECTOR_URL" > yubihsm_pkcs11.conf
          export YUBIHSM_PKCS11_CONF=`pwd`/yubihsm_pkcs11.conf
          pkcs11-tool --module pkcs11/yubihsm_pkcs11.so --show-info
